version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql  # MySQLデータの永続化
      - ./my.cnf:/config/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
  tidy:
    build:
      context: .
      dockerfile: Dockerfile
      target: tidy
    volumes:
      - .:/app
  swag:
    build:
      context: .
      dockerfile: Dockerfile
      target: swagger
    volumes:
      - .:/app
  go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GO_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data:  # ボリュームの定義